server:
  port: 8080

spring:
    datasource:
      url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
          ddl-auto: create
          dialect: org.hibernate.dialect.MySQL8Dialect
    application:
      name: PRODUCT-SERVICE
    config:
      import: configserver:http://localhost:9296


    cloud:
        compatibility-verifier:
          enabled: false

#eureka:
#  instance:
#    prefer-ip-address: true
#    client:
#      fetch-registry: true
#      register-with-eureka: true
#      service-url:
#        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localost:8761/eureka}
